# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(439, 652)
        MainWindow.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"font: 8pt \"Segoe Print\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 391, 321))
        self.tableWidget.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(208, 217, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 540, 121, 51))
        self.pushButton.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(131, 255, 204);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 460, 331, 41))
        self.label.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(131, 255, 204);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QtCore.QRect(90, 380, 82, 17))
        self.radioButton.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(131, 255, 204);")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(250, 380, 101, 17))
        self.radioButton_2.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(131, 255, 204);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 0, 151, 21))
        self.label_2.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(131, 255, 204);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 440, 151, 16))
        self.label_3.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(131, 255, 204);")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 439, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "ПОКУПКА"))
        self.radioButton.setText(_translate("MainWindow", "месяц"))
        self.radioButton_2.setText(_translate("MainWindow", "все вермя"))
        self.label_2.setText(_translate("MainWindow", "История покупок"))
        self.label_3.setText(_translate("MainWindow", "итог:"))
