# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(362, 454)
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nameregline = QtWidgets.QLineEdit(self.centralwidget)
        self.nameregline.setGeometry(QtCore.QRect(70, 110, 261, 31))
        self.nameregline.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.nameregline.setStyleSheet("background-color: rgb(255, 213, 246);")
        self.nameregline.setObjectName("nameregline")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 110, 51, 21))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label.setStyleSheet("\n"
"font: 8pt \"Poor Richard\";\n"
"background-color: rgb(255, 213, 246);\n"
"")
        self.label.setObjectName("label")
        self.passwordregline = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordregline.setGeometry(QtCore.QRect(70, 170, 261, 31))
        self.passwordregline.setStyleSheet("background-color: rgb(255, 213, 246);")
        self.passwordregline.setObjectName("passwordregline")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 51, 21))
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_2.setStyleSheet("\n"
"font: 8pt \"Poor Richard\";\n"
"background-color: rgb(255, 213, 246);")
        self.label_2.setObjectName("label_2")
        self.reg2_but = QtWidgets.QPushButton(self.centralwidget)
        self.reg2_but.setGeometry(QtCore.QRect(100, 320, 141, 41))
        self.reg2_but.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(255, 213, 246);")
        self.reg2_but.setObjectName("reg2_but")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, -20, 91, 121))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Downloads/imgonline-com-ua-Resize-aOo4K6gmkq6X2ZG.jpg"))
        self.label_3.setObjectName("label_3")
        self.stronglabel = QtWidgets.QLabel(self.centralwidget)
        self.stronglabel.setGeometry(QtCore.QRect(90, 210, 191, 16))
        self.stronglabel.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.stronglabel.setText("")
        self.stronglabel.setObjectName("stronglabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 362, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ИМЯ:"))
        self.label_2.setText(_translate("MainWindow", "Пароль:"))
        self.reg2_but.setText(_translate("MainWindow", "Регестрация"))
